// examples/react-app/src/App.js
import * as React from 'react';

import logo from './logo.svg';
import './App.css';

import '@progress/kendo-theme-default';
import './kendo-vanilla-ui/button'

class CustomComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {count: 0};
    this.increment = this.increment.bind(this);
  }
  
  increment(event) {
    this.setState({count: this.state.count+1});
  }
  
  render() {
    return (
    	<div>
        <kendo-web-button text={this.state.count} onClick={this.increment}></kendo-web-button>
      </div>
    );
  }
}

function App() {
  return (
    <div className="App">
      <img src={logo} className="App-logo" alt="logo" />
      <CustomComponent />
    </div>
  );
}

export default App;

// examples/solid/src/App.jsx
import logo from './assets/logo.svg';
import vite from './assets/vite.svg';
import styles from './App.module.css';

import { createSignal, createEffect } from "solid-js";

import '../../../src/index'
import '@progress/kendo-theme-default'

function App() {
  const [count,setCount] = createSignal(0);
  const [text, setText] = createSignal(`Count is: ${count()}`);
  const increment = () => setCount(count => count + 1)

  createEffect(() => setText(`Count is: ${count()}`));

  return (
    <div>
        <div>
          <img src={vite} class={styles.logo} alt="Vite logo" />
          <img src={logo} class={styles.logo} alt="Lit logo" />
        </div>
        <h1 class={styles.header}>Vite + Solid</h1>
        <button is="kendo-button" text={text()} icon="gear" onClick={increment}></button>
    </div>
  );
}

export default App;
