// examples/angular/src/app/app.component.ts
import { Component } from '@angular/core';

import '../../../../src/button';
import './hello-world'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['../../../../node_modules/@progress/kendo-theme-default']
})
export class AppComponent {
  title = 'angular';
}

  <img
    class="logo"
    width="40"
    alt="Angular Logo"
    src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
  />

  <h1>Angular</h1>

  <kendo-button is="kendo-button" text="Count is" icon="gear"></kendo-button>
  
  <hello-world></hello-world>

// examples/solid/src/App.jsx
import logo from './assets/logo.svg';
import vite from './assets/vite.svg';
import styles from './App.module.css';

import { createSignal, createEffect } from "solid-js";

import '../../../src/index'
import '@progress/kendo-theme-default'

function App() {
  const [count,setCount] = createSignal(0);
  const [text, setText] = createSignal(`Count is: ${count()}`);
  const increment = () => setCount(count => count + 1)

  createEffect(() => setText(`Count is: ${count()}`));

  return (
    <div>
        <div>
          <img src={vite} class={styles.logo} alt="Vite logo" />
          <img src={logo} class={styles.logo} alt="Lit logo" />
        </div>
        <h1 class={styles.header}>Vite + Solid</h1>
        <button is="kendo-button" text={text()} icon="gear" onClick={increment}></button>
    </div>
  );
}

export default App;
